# Generated by Django 4.2.14 on 2024-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0002_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_employee", models.CharField(max_length=1600)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="task_title",
            field=models.CharField(default="ajit", max_length=150000),
            preserve_default=False,
        ),
    ]
