# Generated by Django 4.2.14 on 2024-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0003_employee_task_task_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="task_status", new_name="task_completed",
        ),
        migrations.AddField(
            model_name="task",
            name="task_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="task_started",
            field=models.BooleanField(default=False),
        ),
    ]
