# Generated by Django 4.2.14 on 2024-08-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0004_rename_task_status_task_task_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="employee_name",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="sub_task.employee",
            ),
        ),
    ]
