# Generated by Django 4.2.14 on 2024-08-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0005_task_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_deadline",
            field=models.DateTimeField(default="2024-01-01"),
            preserve_default=False,
        ),
    ]
