# Generated by Django 4.2.14 on 2024-08-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0006_project_project_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project_timelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_deadline", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(model_name="project", name="project_deadline",),
        migrations.AddField(
            model_name="task",
            name="task_created_on",
            field=models.DateTimeField(auto_created=True, default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="project_submission_date",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="sub_task.project_timelines",
            ),
        ),
    ]
