# Generated by Django 4.2.14 on 2024-08-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0007_project_timelines_remove_project_project_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_timelines",
            name="project_name",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="sub_task.project",
            ),
        ),
    ]
