# Generated by Django 4.2.14 on 2024-08-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sub_task", "0008_project_timelines_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
